############################################################
##
## Read up on parameters on
## https://docs.prylabs.network/docs/prysm-usage/parameters/
##
############################################################

datadir: /data

##############
# Connectivity
beacon-rpc-provider: haproxy:14000
monitoring-host: 0.0.0.0
monitoring-port: 8680
rpc-host: 0.0.0.0

# Enables historical attestation detection for the slasher
enable-historical-detection: no

spans-cache-size: 1500